spring.application.name=task-tracker
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

tasktracker.max-tasks=6
tasktracker.default-page-size=2